### ISSUE TITLE
Add new entry

### ISSUE THREAD

**Issue by gambledor** [nrosvall/titan#2]
When I try to add a new entry i get the following erro

> Error: no such table: entries
> Failed to add a new entry.

**Comment by nrosvall** [comment]
Hi, Did you first create new database? titan --init /home/user/passwords.db (or any path you want)

**Comment by nrosvall** [comment]
Path should a full path, otherwise Titan might not find the database if you're in a different directory than the database.

**Comment by gambledor** [comment]
for some reason I had the file .titan.lock messed up.
I deleted it and everything started to work
