### ISSUE TITLE
make on CentOS 6

### ISSUE THREAD

**Issue by limer-org** [nrosvall/titan#4]
Installed:
sqlite-devel
gcc 4.4.7
openssl-devel

After 'make':
gcc -std=c99 -Wall -g -c cmd_ui.c -o cmd_ui.o
gcc -std=c99 -Wall -g -c crypto.c -o crypto.o
gcc -std=c99 -Wall -g -c db.c -o db.o
gcc -std=c99 -Wall -g -c entry.c -o entry.o
gcc -std=c99 -Wall -g -c pwd-gen.c -o pwd-gen.o
gcc -std=c99 -Wall -g -c titan.c -o titan.o
gcc -std=c99 -Wall -g -c utils.c -o utils.o
gcc  cmd_ui.o  crypto.o  db.o  entry.o  pwd-gen.o  titan.o  utils.o -lcrypto -lsqlite3 -o titan
pwd-gen.o: In function `generate_password':
/root/titan/pwd-gen.c:69: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status

**Comment by limer-org** [comment]
When I change this line in MakeFile - installation is complete and everything is good
%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@ -lrt

$(PROG): $(OBJS)
	$(CC) $(OBJS) $(LIBS) -o $@ -lrt

**Comment by nrosvall** [comment]
Thanks I'll fix that as soon as possible.

**Comment by nrosvall** [comment]
This is now fixed in the devel branch.
